### ISSUE TITLE
Not working with reactjs

### ISSUE THREAD

**Issue by dsharu** [bassarisse/google-spreadsheet-to-json#17] opened 2017-11-02 22:02 UTC
I installed this package and upon issuing a simple import statement in my react code, it failed with bunch of compilation errors saying "You may need an appropriate loader to handle this file type"

This is my import statement.
import gsjson from 'google-spreadsheet-to-json'

Any idea why?

**Comment by bassarisse** [comment] 2017-11-03 17:12
Not sure about the error per se (seems to me that it is generated by Webpack), but browser environments are not supported. Sorry =/
Closing the issue as this is currently by design.

**Closed as completed by bassarisse** 2017-11-03 17:12 UTC
